"use client"

import { useState, useEffect } from "react"

interface DashboardData {
  acceptance_rates: Array<{
    name: string
    acceptance_rate: number
    location: string
    type: string
    enrollment: number
  }>
  tuition_analysis: Array<{
    name: string
    tuition: number
    sat_average: number
    acceptance_rate: number
    location: string
    type: string
    enrollment: number
    graduation_rate: number
    student_faculty_ratio: number
  }>
  sat_distribution: Array<{
    range: string
    count: number
    midpoint: number
  }>
  demographics: Array<{
    region: string
    white: number
    asian: number
    hispanic: number
    black: number
    other: number
  }>
  summary_stats: {
    avg_acceptance_rate: number
    total_applications: string
    avg_tuition: number
    avg_sat: number
  }
  regional_analysis: Record<string, any>
}

export function useDashboardData() {
  const [data, setData] = useState<DashboardData | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [selectedColleges, setSelectedColleges] = useState<string[]>([])
  const [filteredData, setFilteredData] = useState<DashboardData | null>(null)

  useEffect(() => {
    const loadData = async () => {
      try {
        await new Promise((resolve) => setTimeout(resolve, 1000))

        const mockData: DashboardData = {
          acceptance_rates: [
            {
              name: "Harvard University",
              acceptance_rate: 5.2,
              location: "Cambridge, MA",
              type: "Private",
              enrollment: 22947,
            },
            {
              name: "Stanford University",
              acceptance_rate: 4.8,
              location: "Stanford, CA",
              type: "Private",
              enrollment: 17249,
            },
            { name: "MIT", acceptance_rate: 7.3, location: "Cambridge, MA", type: "Private", enrollment: 11934 },
            {
              name: "Yale University",
              acceptance_rate: 6.1,
              location: "New Haven, CT",
              type: "Private",
              enrollment: 13433,
            },
            {
              name: "Princeton University",
              acceptance_rate: 5.8,
              location: "Princeton, NJ",
              type: "Private",
              enrollment: 5394,
            },
            {
              name: "Columbia University",
              acceptance_rate: 6.7,
              location: "New York, NY",
              type: "Private",
              enrollment: 31455,
            },
            {
              name: "University of Chicago",
              acceptance_rate: 7.4,
              location: "Chicago, IL",
              type: "Private",
              enrollment: 16445,
            },
            {
              name: "University of Pennsylvania",
              acceptance_rate: 8.1,
              location: "Philadelphia, PA",
              type: "Private",
              enrollment: 25860,
            },
            {
              name: "Northwestern University",
              acceptance_rate: 9.3,
              location: "Evanston, IL",
              type: "Private",
              enrollment: 21946,
            },
            {
              name: "Duke University",
              acceptance_rate: 10.2,
              location: "Durham, NC",
              type: "Private",
              enrollment: 16130,
            },
            {
              name: "Johns Hopkins University",
              acceptance_rate: 11.5,
              location: "Baltimore, MD",
              type: "Private",
              enrollment: 26402,
            },
            {
              name: "Dartmouth College",
              acceptance_rate: 10.9,
              location: "Hanover, NH",
              type: "Private",
              enrollment: 6572,
            },
            {
              name: "Brown University",
              acceptance_rate: 9.6,
              location: "Providence, RI",
              type: "Private",
              enrollment: 10696,
            },
            {
              name: "Cornell University",
              acceptance_rate: 15.1,
              location: "Ithaca, NY",
              type: "Private",
              enrollment: 23620,
            },
            {
              name: "Vanderbilt University",
              acceptance_rate: 12.7,
              location: "Nashville, TN",
              type: "Private",
              enrollment: 13131,
            },
            {
              name: "Rice University",
              acceptance_rate: 15.3,
              location: "Houston, TX",
              type: "Private",
              enrollment: 7124,
            },
            {
              name: "Washington University in St. Louis",
              acceptance_rate: 16.4,
              location: "St. Louis, MO",
              type: "Private",
              enrollment: 15852,
            },
            {
              name: "Emory University",
              acceptance_rate: 19.2,
              location: "Atlanta, GA",
              type: "Private",
              enrollment: 14513,
            },
            {
              name: "Georgetown University",
              acceptance_rate: 17.8,
              location: "Washington, DC",
              type: "Private",
              enrollment: 19204,
            },
            {
              name: "Carnegie Mellon University",
              acceptance_rate: 22.3,
              location: "Pittsburgh, PA",
              type: "Private",
              enrollment: 14799,
            },
            {
              name: "University of Notre Dame",
              acceptance_rate: 19.7,
              location: "Notre Dame, IN",
              type: "Private",
              enrollment: 12681,
            },
            {
              name: "Wake Forest University",
              acceptance_rate: 30.4,
              location: "Winston-Salem, NC",
              type: "Private",
              enrollment: 5441,
            },
            {
              name: "Tufts University",
              acceptance_rate: 16.9,
              location: "Medford, MA",
              type: "Private",
              enrollment: 11878,
            },
            {
              name: "Boston College",
              acceptance_rate: 28.2,
              location: "Chestnut Hill, MA",
              type: "Private",
              enrollment: 14934,
            },
            {
              name: "New York University",
              acceptance_rate: 32.1,
              location: "New York, NY",
              type: "Private",
              enrollment: 51848,
            },
            {
              name: "University of Southern California",
              acceptance_rate: 16.1,
              location: "Los Angeles, CA",
              type: "Private",
              enrollment: 47310,
            },
            {
              name: "Northeastern University",
              acceptance_rate: 20.5,
              location: "Boston, MA",
              type: "Private",
              enrollment: 22207,
            },
            {
              name: "Case Western Reserve University",
              acceptance_rate: 35.8,
              location: "Cleveland, OH",
              type: "Private",
              enrollment: 11824,
            },
            {
              name: "Tulane University",
              acceptance_rate: 13.2,
              location: "New Orleans, LA",
              type: "Private",
              enrollment: 13927,
            },
            { name: "UC Berkeley", acceptance_rate: 17.5, location: "Berkeley, CA", type: "Public", enrollment: 42327 },
            { name: "UCLA", acceptance_rate: 14.3, location: "Los Angeles, CA", type: "Public", enrollment: 44371 },
            {
              name: "UC San Diego",
              acceptance_rate: 38.3,
              location: "La Jolla, CA",
              type: "Public",
              enrollment: 38736,
            },
            {
              name: "UC Santa Barbara",
              acceptance_rate: 37.2,
              location: "Santa Barbara, CA",
              type: "Public",
              enrollment: 26314,
            },
            { name: "UC Irvine", acceptance_rate: 41.1, location: "Irvine, CA", type: "Public", enrollment: 36032 },
            { name: "UC Davis", acceptance_rate: 49.0, location: "Davis, CA", type: "Public", enrollment: 38167 },
            {
              name: "UC Santa Cruz",
              acceptance_rate: 65.2,
              location: "Santa Cruz, CA",
              type: "Public",
              enrollment: 19700,
            },
            {
              name: "UC Riverside",
              acceptance_rate: 70.1,
              location: "Riverside, CA",
              type: "Public",
              enrollment: 26809,
            },
            { name: "UC Merced", acceptance_rate: 89.0, location: "Merced, CA", type: "Public", enrollment: 9544 },
            {
              name: "University of Michigan",
              acceptance_rate: 26.5,
              location: "Ann Arbor, MI",
              type: "Public",
              enrollment: 46716,
            },
            {
              name: "University of Virginia",
              acceptance_rate: 30.2,
              location: "Charlottesville, VA",
              type: "Public",
              enrollment: 25018,
            },
            {
              name: "University of North Carolina at Chapel Hill",
              acceptance_rate: 25.2,
              location: "Chapel Hill, NC",
              type: "Public",
              enrollment: 30011,
            },
            {
              name: "University of Texas at Austin",
              acceptance_rate: 38.5,
              location: "Austin, TX",
              type: "Public",
              enrollment: 51832,
            },
            {
              name: "University of Florida",
              acceptance_rate: 37.1,
              location: "Gainesville, FL",
              type: "Public",
              enrollment: 52218,
            },
            {
              name: "University of Washington",
              acceptance_rate: 56.3,
              location: "Seattle, WA",
              type: "Public",
              enrollment: 47400,
            },
            {
              name: "University of Wisconsin-Madison",
              acceptance_rate: 64.7,
              location: "Madison, WI",
              type: "Public",
              enrollment: 44411,
            },
            {
              name: "University of Illinois Urbana-Champaign",
              acceptance_rate: 62.9,
              location: "Champaign, IL",
              type: "Public",
              enrollment: 48216,
            },
            {
              name: "Georgia Institute of Technology",
              acceptance_rate: 23.6,
              location: "Atlanta, GA",
              type: "Public",
              enrollment: 36848,
            },
            {
              name: "University of Georgia",
              acceptance_rate: 49.8,
              location: "Athens, GA",
              type: "Public",
              enrollment: 38920,
            },
            {
              name: "Penn State University",
              acceptance_rate: 76.2,
              location: "University Park, PA",
              type: "Public",
              enrollment: 46810,
            },
            {
              name: "Ohio State University",
              acceptance_rate: 68.5,
              location: "Columbus, OH",
              type: "Public",
              enrollment: 61369,
            },
            {
              name: "University of Maryland",
              acceptance_rate: 51.0,
              location: "College Park, MD",
              type: "Public",
              enrollment: 40521,
            },
            {
              name: "Purdue University",
              acceptance_rate: 69.0,
              location: "West Lafayette, IN",
              type: "Public",
              enrollment: 45500,
            },
            {
              name: "University of Minnesota",
              acceptance_rate: 75.2,
              location: "Minneapolis, MN",
              type: "Public",
              enrollment: 50943,
            },
            {
              name: "University of Colorado Boulder",
              acceptance_rate: 84.2,
              location: "Boulder, CO",
              type: "Public",
              enrollment: 35581,
            },
            {
              name: "University of Arizona",
              acceptance_rate: 87.0,
              location: "Tucson, AZ",
              type: "Public",
              enrollment: 45918,
            },
            {
              name: "Arizona State University",
              acceptance_rate: 88.1,
              location: "Tempe, AZ",
              type: "Public",
              enrollment: 80065,
            },
            {
              name: "University of Alabama",
              acceptance_rate: 83.3,
              location: "Tuscaloosa, AL",
              type: "Public",
              enrollment: 38563,
            },
            {
              name: "University of Oregon",
              acceptance_rate: 84.4,
              location: "Eugene, OR",
              type: "Public",
              enrollment: 22249,
            },
            {
              name: "University of South Carolina",
              acceptance_rate: 68.5,
              location: "Columbia, SC",
              type: "Public",
              enrollment: 35364,
            },
            {
              name: "University of Tennessee",
              acceptance_rate: 78.8,
              location: "Knoxville, TN",
              type: "Public",
              enrollment: 29460,
            },
            {
              name: "University of Kentucky",
              acceptance_rate: 95.0,
              location: "Lexington, KY",
              type: "Public",
              enrollment: 30720,
            },
            {
              name: "University of Arkansas",
              acceptance_rate: 78.2,
              location: "Fayetteville, AR",
              type: "Public",
              enrollment: 27562,
            },
            {
              name: "University of Oklahoma",
              acceptance_rate: 69.1,
              location: "Norman, OK",
              type: "Public",
              enrollment: 28840,
            },
            {
              name: "University of Kansas",
              acceptance_rate: 93.7,
              location: "Lawrence, KS",
              type: "Public",
              enrollment: 27939,
            },
            {
              name: "University of Nebraska",
              acceptance_rate: 78.6,
              location: "Lincoln, NE",
              type: "Public",
              enrollment: 25820,
            },
            {
              name: "University of Iowa",
              acceptance_rate: 86.1,
              location: "Iowa City, IA",
              type: "Public",
              enrollment: 31240,
            },
            {
              name: "University of Missouri",
              acceptance_rate: 81.4,
              location: "Columbia, MO",
              type: "Public",
              enrollment: 30870,
            },
            {
              name: "Williams College",
              acceptance_rate: 15.2,
              location: "Williamstown, MA",
              type: "Private",
              enrollment: 2099,
            },
            {
              name: "Amherst College",
              acceptance_rate: 13.7,
              location: "Amherst, MA",
              type: "Private",
              enrollment: 1855,
            },
            {
              name: "Swarthmore College",
              acceptance_rate: 12.2,
              location: "Swarthmore, PA",
              type: "Private",
              enrollment: 1647,
            },
            {
              name: "Wellesley College",
              acceptance_rate: 22.6,
              location: "Wellesley, MA",
              type: "Private",
              enrollment: 2474,
            },
            {
              name: "Middlebury College",
              acceptance_rate: 17.4,
              location: "Middlebury, VT",
              type: "Private",
              enrollment: 2526,
            },
            {
              name: "Bowdoin College",
              acceptance_rate: 10.9,
              location: "Brunswick, ME",
              type: "Private",
              enrollment: 1828,
            },
            {
              name: "Carleton College",
              acceptance_rate: 21.8,
              location: "Northfield, MN",
              type: "Private",
              enrollment: 2057,
            },
            {
              name: "Pomona College",
              acceptance_rate: 10.3,
              location: "Claremont, CA",
              type: "Private",
              enrollment: 1703,
            },
            {
              name: "Claremont McKenna College",
              acceptance_rate: 12.9,
              location: "Claremont, CA",
              type: "Private",
              enrollment: 1338,
            },
            {
              name: "Davidson College",
              acceptance_rate: 20.2,
              location: "Davidson, NC",
              type: "Private",
              enrollment: 1973,
            },
            {
              name: "Haverford College",
              acceptance_rate: 18.4,
              location: "Haverford, PA",
              type: "Private",
              enrollment: 1310,
            },
            {
              name: "Vassar College",
              acceptance_rate: 27.0,
              location: "Poughkeepsie, NY",
              type: "Private",
              enrollment: 2450,
            },
            {
              name: "Colby College",
              acceptance_rate: 13.9,
              location: "Waterville, ME",
              type: "Private",
              enrollment: 2000,
            },
            {
              name: "Hamilton College",
              acceptance_rate: 18.2,
              location: "Clinton, NY",
              type: "Private",
              enrollment: 1968,
            },
            {
              name: "Bates College",
              acceptance_rate: 18.1,
              location: "Lewiston, ME",
              type: "Private",
              enrollment: 1792,
            },
            {
              name: "Florida State University",
              acceptance_rate: 41.1,
              location: "Tallahassee, FL",
              type: "Public",
              enrollment: 41005,
            },
            {
              name: "University of Miami",
              acceptance_rate: 33.2,
              location: "Coral Gables, FL",
              type: "Private",
              enrollment: 17331,
            },
            {
              name: "Texas A&M University",
              acceptance_rate: 67.1,
              location: "College Station, TX",
              type: "Public",
              enrollment: 70418,
            },
            {
              name: "Virginia Tech",
              acceptance_rate: 70.1,
              location: "Blacksburg, VA",
              type: "Public",
              enrollment: 37024,
            },
            {
              name: "North Carolina State University",
              acceptance_rate: 51.3,
              location: "Raleigh, NC",
              type: "Public",
              enrollment: 36304,
            },
            {
              name: "Clemson University",
              acceptance_rate: 51.0,
              location: "Clemson, SC",
              type: "Public",
              enrollment: 25822,
            },
            {
              name: "Auburn University",
              acceptance_rate: 85.0,
              location: "Auburn, AL",
              type: "Public",
              enrollment: 30440,
            },
            {
              name: "University of Connecticut",
              acceptance_rate: 56.3,
              location: "Storrs, CT",
              type: "Public",
              enrollment: 27412,
            },
            {
              name: "University of Delaware",
              acceptance_rate: 73.8,
              location: "Newark, DE",
              type: "Public",
              enrollment: 23744,
            },
            {
              name: "University of Vermont",
              acceptance_rate: 67.5,
              location: "Burlington, VT",
              type: "Public",
              enrollment: 13796,
            },
            {
              name: "University of New Hampshire",
              acceptance_rate: 87.0,
              location: "Durham, NH",
              type: "Public",
              enrollment: 15398,
            },
            {
              name: "University of Maine",
              acceptance_rate: 94.0,
              location: "Orono, ME",
              type: "Public",
              enrollment: 11741,
            },
            {
              name: "University of Rhode Island",
              acceptance_rate: 76.4,
              location: "Kingston, RI",
              type: "Public",
              enrollment: 17649,
            },
            {
              name: "University of Massachusetts Amherst",
              acceptance_rate: 64.2,
              location: "Amherst, MA",
              type: "Public",
              enrollment: 31635,
            },
          ],
          tuition_analysis: [
            {
              name: "Harvard University",
              tuition: 54002,
              sat_average: 1520,
              acceptance_rate: 5.2,
              location: "Cambridge, MA",
              type: "Private",
              enrollment: 22947,
              graduation_rate: 97,
              student_faculty_ratio: 7,
            },
            {
              name: "Stanford University",
              tuition: 56169,
              sat_average: 1505,
              acceptance_rate: 4.8,
              location: "Stanford, CA",
              type: "Private",
              enrollment: 17249,
              graduation_rate: 94,
              student_faculty_ratio: 5,
            },
            {
              name: "MIT",
              tuition: 53790,
              sat_average: 1535,
              acceptance_rate: 7.3,
              location: "Cambridge, MA",
              type: "Private",
              enrollment: 11934,
              graduation_rate: 93,
              student_faculty_ratio: 3,
            },
            {
              name: "Yale University",
              tuition: 57700,
              sat_average: 1515,
              acceptance_rate: 6.1,
              location: "New Haven, CT",
              type: "Private",
              enrollment: 13433,
              graduation_rate: 96,
              student_faculty_ratio: 6,
            },
            {
              name: "Princeton University",
              tuition: 56010,
              sat_average: 1510,
              acceptance_rate: 5.8,
              location: "Princeton, NJ",
              type: "Private",
              enrollment: 5394,
              graduation_rate: 97,
              student_faculty_ratio: 5,
            },
            {
              name: "Columbia University",
              tuition: 61850,
              sat_average: 1505,
              acceptance_rate: 6.7,
              location: "New York, NY",
              type: "Private",
              enrollment: 31455,
              graduation_rate: 95,
              student_faculty_ratio: 6,
            },
            {
              name: "University of Chicago",
              tuition: 59298,
              sat_average: 1520,
              acceptance_rate: 7.4,
              location: "Chicago, IL",
              type: "Private",
              enrollment: 16445,
              graduation_rate: 94,
              student_faculty_ratio: 5,
            },
            {
              name: "University of Pennsylvania",
              tuition: 58620,
              sat_average: 1500,
              acceptance_rate: 8.1,
              location: "Philadelphia, PA",
              type: "Private",
              enrollment: 25860,
              graduation_rate: 95,
              student_faculty_ratio: 6,
            },
            {
              name: "Northwestern University",
              tuition: 58701,
              sat_average: 1490,
              acceptance_rate: 9.3,
              location: "Evanston, IL",
              type: "Private",
              enrollment: 21946,
              graduation_rate: 94,
              student_faculty_ratio: 6,
            },
            {
              name: "Duke University",
              tuition: 58031,
              sat_average: 1485,
              acceptance_rate: 10.2,
              location: "Durham, NC",
              type: "Private",
              enrollment: 16130,
              graduation_rate: 95,
              student_faculty_ratio: 6,
            },
            {
              name: "Johns Hopkins University",
              tuition: 57010,
              sat_average: 1480,
              acceptance_rate: 11.5,
              location: "Baltimore, MD",
              type: "Private",
              enrollment: 26402,
              graduation_rate: 93,
              student_faculty_ratio: 7,
            },
            {
              name: "Dartmouth College",
              tuition: 58953,
              sat_average: 1475,
              acceptance_rate: 10.9,
              location: "Hanover, NH",
              type: "Private",
              enrollment: 6572,
              graduation_rate: 95,
              student_faculty_ratio: 7,
            },
            {
              name: "Brown University",
              tuition: 58404,
              sat_average: 1470,
              acceptance_rate: 9.6,
              location: "Providence, RI",
              type: "Private",
              enrollment: 10696,
              graduation_rate: 95,
              student_faculty_ratio: 7,
            },
            {
              name: "Cornell University",
              tuition: 57222,
              sat_average: 1465,
              acceptance_rate: 15.1,
              location: "Ithaca, NY",
              type: "Private",
              enrollment: 23620,
              graduation_rate: 93,
              student_faculty_ratio: 9,
            },
            {
              name: "Vanderbilt University",
              tuition: 54158,
              sat_average: 1465,
              acceptance_rate: 12.7,
              location: "Nashville, TN",
              type: "Private",
              enrollment: 13131,
              graduation_rate: 93,
              student_faculty_ratio: 8,
            },
            {
              name: "Rice University",
              tuition: 50920,
              sat_average: 1460,
              acceptance_rate: 15.3,
              location: "Houston, TX",
              type: "Private",
              enrollment: 7124,
              graduation_rate: 94,
              student_faculty_ratio: 6,
            },
            {
              name: "Washington University in St. Louis",
              tuition: 57750,
              sat_average: 1455,
              acceptance_rate: 16.4,
              location: "St. Louis, MO",
              type: "Private",
              enrollment: 15852,
              graduation_rate: 94,
              student_faculty_ratio: 7,
            },
            {
              name: "Emory University",
              tuition: 53868,
              sat_average: 1450,
              acceptance_rate: 19.2,
              location: "Atlanta, GA",
              type: "Private",
              enrollment: 14513,
              graduation_rate: 90,
              student_faculty_ratio: 9,
            },
            {
              name: "Georgetown University",
              tuition: 59957,
              sat_average: 1445,
              acceptance_rate: 17.8,
              location: "Washington, DC",
              type: "Private",
              enrollment: 19204,
              graduation_rate: 94,
              student_faculty_ratio: 11,
            },
            {
              name: "Carnegie Mellon University",
              tuition: 58924,
              sat_average: 1470,
              acceptance_rate: 22.3,
              location: "Pittsburgh, PA",
              type: "Private",
              enrollment: 14799,
              graduation_rate: 89,
              student_faculty_ratio: 10,
            },
            {
              name: "University of Notre Dame",
              tuition: 57699,
              sat_average: 1440,
              acceptance_rate: 19.7,
              location: "Notre Dame, IN",
              type: "Private",
              enrollment: 12681,
              graduation_rate: 95,
              student_faculty_ratio: 10,
            },
            {
              name: "Wake Forest University",
              tuition: 58226,
              sat_average: 1435,
              acceptance_rate: 30.4,
              location: "Winston-Salem, NC",
              type: "Private",
              enrollment: 5441,
              graduation_rate: 88,
              student_faculty_ratio: 10,
            },
            {
              name: "Tufts University",
              tuition: 58578,
              sat_average: 1430,
              acceptance_rate: 16.9,
              location: "Medford, MA",
              type: "Private",
              enrollment: 11878,
              graduation_rate: 93,
              student_faculty_ratio: 9,
            },
            {
              name: "Boston College",
              tuition: 59050,
              sat_average: 1425,
              acceptance_rate: 28.2,
              location: "Chestnut Hill, MA",
              type: "Private",
              enrollment: 14934,
              graduation_rate: 92,
              student_faculty_ratio: 11,
            },
            {
              name: "New York University",
              tuition: 53308,
              sat_average: 1420,
              acceptance_rate: 32.1,
              location: "New York, NY",
              type: "Private",
              enrollment: 51848,
              graduation_rate: 85,
              student_faculty_ratio: 9,
            },
            {
              name: "University of Southern California",
              tuition: 58195,
              sat_average: 1415,
              acceptance_rate: 16.1,
              location: "Los Angeles, CA",
              type: "Private",
              enrollment: 47310,
              graduation_rate: 92,
              student_faculty_ratio: 9,
            },
            {
              name: "Northeastern University",
              tuition: 55452,
              sat_average: 1410,
              acceptance_rate: 20.5,
              location: "Boston, MA",
              type: "Private",
              enrollment: 22207,
              graduation_rate: 89,
              student_faculty_ratio: 14,
            },
            {
              name: "Case Western Reserve University",
              tuition: 51500,
              sat_average: 1405,
              acceptance_rate: 35.8,
              location: "Cleveland, OH",
              type: "Private",
              enrollment: 11824,
              graduation_rate: 82,
              student_faculty_ratio: 11,
            },
            {
              name: "Tulane University",
              tuition: 58446,
              sat_average: 1400,
              acceptance_rate: 13.2,
              location: "New Orleans, LA",
              type: "Private",
              enrollment: 13927,
              graduation_rate: 83,
              student_faculty_ratio: 8,
            },
            {
              name: "UC Berkeley",
              tuition: 14226,
              sat_average: 1415,
              acceptance_rate: 17.5,
              location: "Berkeley, CA",
              type: "Public",
              enrollment: 42327,
              graduation_rate: 91,
              student_faculty_ratio: 20,
            },
            {
              name: "UCLA",
              tuition: 13249,
              sat_average: 1405,
              acceptance_rate: 14.3,
              location: "Los Angeles, CA",
              type: "Public",
              enrollment: 44371,
              graduation_rate: 91,
              student_faculty_ratio: 18,
            },
            {
              name: "UC San Diego",
              tuition: 14170,
              sat_average: 1350,
              acceptance_rate: 38.3,
              location: "La Jolla, CA",
              type: "Public",
              enrollment: 38736,
              graduation_rate: 87,
              student_faculty_ratio: 19,
            },
            {
              name: "UC Santa Barbara",
              tuition: 14391,
              sat_average: 1340,
              acceptance_rate: 37.2,
              location: "Santa Barbara, CA",
              type: "Public",
              enrollment: 26314,
              graduation_rate: 82,
              student_faculty_ratio: 22,
            },
            {
              name: "UC Irvine",
              tuition: 13727,
              sat_average: 1335,
              acceptance_rate: 41.1,
              location: "Irvine, CA",
              type: "Public",
              enrollment: 36032,
              graduation_rate: 83,
              student_faculty_ratio: 19,
            },
            {
              name: "UC Davis",
              tuition: 14495,
              sat_average: 1330,
              acceptance_rate: 49.0,
              location: "Davis, CA",
              type: "Public",
              enrollment: 38167,
              graduation_rate: 85,
              student_faculty_ratio: 20,
            },
            {
              name: "UC Santa Cruz",
              tuition: 14028,
              sat_average: 1280,
              acceptance_rate: 65.2,
              location: "Santa Cruz, CA",
              type: "Public",
              enrollment: 19700,
              graduation_rate: 77,
              student_faculty_ratio: 24,
            },
            {
              name: "UC Riverside",
              tuition: 13853,
              sat_average: 1240,
              acceptance_rate: 70.1,
              location: "Riverside, CA",
              type: "Public",
              enrollment: 26809,
              graduation_rate: 73,
              student_faculty_ratio: 23,
            },
            {
              name: "UC Merced",
              tuition: 13538,
              sat_average: 1200,
              acceptance_rate: 89.0,
              location: "Merced, CA",
              type: "Public",
              enrollment: 9544,
              graduation_rate: 68,
              student_faculty_ratio: 21,
            },
            {
              name: "University of Michigan",
              tuition: 15948,
              sat_average: 1395,
              acceptance_rate: 26.5,
              location: "Ann Arbor, MI",
              type: "Public",
              enrollment: 46716,
              graduation_rate: 91,
              student_faculty_ratio: 15,
            },
            {
              name: "University of Virginia",
              tuition: 17300,
              sat_average: 1385,
              acceptance_rate: 30.2,
              location: "Charlottesville, VA",
              type: "Public",
              enrollment: 25018,
              graduation_rate: 94,
              student_faculty_ratio: 15,
            },
            {
              name: "University of North Carolina at Chapel Hill",
              tuition: 8980,
              sat_average: 1375,
              acceptance_rate: 25.2,
              location: "Chapel Hill, NC",
              type: "Public",
              enrollment: 30011,
              graduation_rate: 90,
              student_faculty_ratio: 13,
            },
            {
              name: "University of Texas at Austin",
              tuition: 11448,
              sat_average: 1365,
              acceptance_rate: 38.5,
              location: "Austin, TX",
              type: "Public",
              enrollment: 51832,
              graduation_rate: 81,
              student_faculty_ratio: 18,
            },
            {
              name: "University of Florida",
              tuition: 6381,
              sat_average: 1355,
              acceptance_rate: 37.1,
              location: "Gainesville, FL",
              type: "Public",
              enrollment: 52218,
              graduation_rate: 87,
              student_faculty_ratio: 21,
            },
            {
              name: "University of Washington",
              tuition: 11745,
              sat_average: 1345,
              acceptance_rate: 56.3,
              location: "Seattle, WA",
              type: "Public",
              enrollment: 47400,
              graduation_rate: 84,
              student_faculty_ratio: 20,
            },
            {
              name: "University of Wisconsin-Madison",
              tuition: 10725,
              sat_average: 1335,
              acceptance_rate: 64.7,
              location: "Madison, WI",
              type: "Public",
              enrollment: 44411,
              graduation_rate: 85,
              student_faculty_ratio: 17,
            },
            {
              name: "University of Illinois Urbana-Champaign",
              tuition: 15868,
              sat_average: 1325,
              acceptance_rate: 62.9,
              location: "Champaign, IL",
              type: "Public",
              enrollment: 48216,
              graduation_rate: 83,
              student_faculty_ratio: 20,
            },
            {
              name: "Georgia Institute of Technology",
              tuition: 12682,
              sat_average: 1415,
              acceptance_rate: 23.6,
              location: "Atlanta, GA",
              type: "Public",
              enrollment: 36848,
              graduation_rate: 85,
              student_faculty_ratio: 22,
            },
            {
              name: "University of Georgia",
              tuition: 11818,
              sat_average: 1315,
              acceptance_rate: 49.8,
              location: "Athens, GA",
              type: "Public",
              enrollment: 38920,
              graduation_rate: 85,
              student_faculty_ratio: 17,
            },
            {
              name: "Penn State University",
              tuition: 18454,
              sat_average: 1305,
              acceptance_rate: 76.2,
              location: "University Park, PA",
              type: "Public",
              enrollment: 46810,
              graduation_rate: 85,
              student_faculty_ratio: 16,
            },
            {
              name: "Ohio State University",
              tuition: 11518,
              sat_average: 1295,
              acceptance_rate: 68.5,
              location: "Columbus, OH",
              type: "Public",
              enrollment: 61369,
              graduation_rate: 83,
              student_faculty_ratio: 19,
            },
            {
              name: "University of Maryland",
              tuition: 10779,
              sat_average: 1285,
              acceptance_rate: 51.0,
              location: "College Park, MD",
              type: "Public",
              enrollment: 40521,
              graduation_rate: 85,
              student_faculty_ratio: 18,
            },
            {
              name: "Purdue University",
              tuition: 10002,
              sat_average: 1275,
              acceptance_rate: 69.0,
              location: "West Lafayette, IN",
              type: "Public",
              enrollment: 45500,
              graduation_rate: 81,
              student_faculty_ratio: 13,
            },
            {
              name: "University of Minnesota",
              tuition: 15027,
              sat_average: 1265,
              acceptance_rate: 75.2,
              location: "Minneapolis, MN",
              type: "Public",
              enrollment: 50943,
              graduation_rate: 78,
              student_faculty_ratio: 17,
            },
            {
              name: "University of Colorado Boulder",
              tuition: 12086,
              sat_average: 1255,
              acceptance_rate: 84.2,
              location: "Boulder, CO",
              type: "Public",
              enrollment: 35581,
              graduation_rate: 70,
              student_faculty_ratio: 18,
            },
            {
              name: "University of Arizona",
              tuition: 12691,
              sat_average: 1245,
              acceptance_rate: 87.0,
              location: "Tucson, AZ",
              type: "Public",
              enrollment: 45918,
              graduation_rate: 63,
              student_faculty_ratio: 23,
            },
            {
              name: "Arizona State University",
              tuition: 11338,
              sat_average: 1235,
              acceptance_rate: 88.1,
              location: "Tempe, AZ",
              type: "Public",
              enrollment: 80065,
              graduation_rate: 67,
              student_faculty_ratio: 23,
            },
            {
              name: "University of Alabama",
              tuition: 11100,
              sat_average: 1225,
              acceptance_rate: 83.3,
              location: "Tuscaloosa, AL",
              type: "Public",
              enrollment: 38563,
              graduation_rate: 68,
              student_faculty_ratio: 20,
            },
            {
              name: "University of Oregon",
              tuition: 12720,
              sat_average: 1215,
              acceptance_rate: 84.4,
              location: "Eugene, OR",
              type: "Public",
              enrollment: 22249,
              graduation_rate: 71,
              student_faculty_ratio: 17,
            },
            {
              name: "Williams College",
              tuition: 59550,
              sat_average: 1485,
              acceptance_rate: 15.2,
              location: "Williamstown, MA",
              type: "Private",
              enrollment: 2099,
              graduation_rate: 95,
              student_faculty_ratio: 7,
            },
            {
              name: "Amherst College",
              tuition: 58640,
              sat_average: 1480,
              acceptance_rate: 13.7,
              location: "Amherst, MA",
              type: "Private",
              enrollment: 1855,
              graduation_rate: 96,
              student_faculty_ratio: 8,
            },
            {
              name: "Swarthmore College",
              tuition: 54256,
              sat_average: 1475,
              acceptance_rate: 12.2,
              location: "Swarthmore, PA",
              type: "Private",
              enrollment: 1647,
              graduation_rate: 94,
              student_faculty_ratio: 8,
            },
            {
              name: "Wellesley College",
              tuition: 58120,
              sat_average: 1470,
              acceptance_rate: 22.6,
              location: "Wellesley, MA",
              type: "Private",
              enrollment: 2474,
              graduation_rate: 91,
              student_faculty_ratio: 8,
            },
            {
              name: "Middlebury College",
              tuition: 58062,
              sat_average: 1465,
              acceptance_rate: 17.4,
              location: "Middlebury, VT",
              type: "Private",
              enrollment: 2526,
              graduation_rate: 93,
              student_faculty_ratio: 8,
            },
            {
              name: "Bowdoin College",
              tuition: 56350,
              sat_average: 1460,
              acceptance_rate: 10.9,
              location: "Brunswick, ME",
              type: "Private",
              enrollment: 1828,
              graduation_rate: 94,
              student_faculty_ratio: 9,
            },
            {
              name: "Carleton College",
              tuition: 58194,
              sat_average: 1455,
              acceptance_rate: 21.8,
              location: "Northfield, MN",
              type: "Private",
              enrollment: 2057,
              graduation_rate: 93,
              student_faculty_ratio: 9,
            },
            {
              name: "Pomona College",
              tuition: 54380,
              sat_average: 1450,
              acceptance_rate: 10.3,
              location: "Claremont, CA",
              type: "Private",
              enrollment: 1703,
              graduation_rate: 94,
              student_faculty_ratio: 8,
            },
            {
              name: "Claremont McKenna College",
              tuition: 56475,
              sat_average: 1445,
              acceptance_rate: 12.9,
              location: "Claremont, CA",
              type: "Private",
              enrollment: 1338,
              graduation_rate: 92,
              student_faculty_ratio: 8,
            },
            {
              name: "Davidson College",
              tuition: 53849,
              sat_average: 1440,
              acceptance_rate: 20.2,
              location: "Davidson, NC",
              type: "Private",
              enrollment: 1973,
              graduation_rate: 93,
              student_faculty_ratio: 10,
            },
            {
              name: "Florida State University",
              tuition: 5656,
              sat_average: 1280,
              acceptance_rate: 41.1,
              location: "Tallahassee, FL",
              type: "Public",
              enrollment: 41005,
              graduation_rate: 80,
              student_faculty_ratio: 21,
            },
            {
              name: "University of Miami",
              tuition: 52080,
              sat_average: 1390,
              acceptance_rate: 33.2,
              location: "Coral Gables, FL",
              type: "Private",
              enrollment: 17331,
              graduation_rate: 83,
              student_faculty_ratio: 12,
            },
            {
              name: "Texas A&M University",
              tuition: 12413,
              sat_average: 1270,
              acceptance_rate: 67.1,
              location: "College Station, TX",
              type: "Public",
              enrollment: 70418,
              graduation_rate: 80,
              student_faculty_ratio: 20,
            },
            {
              name: "Virginia Tech",
              tuition: 13691,
              sat_average: 1260,
              acceptance_rate: 70.1,
              location: "Blacksburg, VA",
              type: "Public",
              enrollment: 37024,
              graduation_rate: 83,
              student_faculty_ratio: 14,
            },
            {
              name: "North Carolina State University",
              tuition: 9058,
              sat_average: 1250,
              acceptance_rate: 51.3,
              location: "Raleigh, NC",
              type: "Public",
              enrollment: 36304,
              graduation_rate: 78,
              student_faculty_ratio: 13,
            },
            {
              name: "Clemson University",
              tuition: 15558,
              sat_average: 1240,
              acceptance_rate: 51.0,
              location: "Clemson, SC",
              type: "Public",
              enrollment: 25822,
              graduation_rate: 82,
              student_faculty_ratio: 16,
            },
            {
              name: "Auburn University",
              tuition: 11796,
              sat_average: 1230,
              acceptance_rate: 85.0,
              location: "Auburn, AL",
              type: "Public",
              enrollment: 30440,
              graduation_rate: 79,
              student_faculty_ratio: 19,
            },
            {
              name: "University of Connecticut",
              tuition: 17834,
              sat_average: 1220,
              acceptance_rate: 56.3,
              location: "Storrs, CT",
              type: "Public",
              enrollment: 27412,
              graduation_rate: 83,
              student_faculty_ratio: 16,
            },
            {
              name: "University of Delaware",
              tuition: 14280,
              sat_average: 1210,
              acceptance_rate: 73.8,
              location: "Newark, DE",
              type: "Public",
              enrollment: 23744,
              graduation_rate: 81,
              student_faculty_ratio: 15,
            },
            {
              name: "University of Vermont",
              tuition: 18890,
              sat_average: 1200,
              acceptance_rate: 67.5,
              location: "Burlington, VT",
              type: "Public",
              enrollment: 13796,
              graduation_rate: 76,
              student_faculty_ratio: 17,
            },
            {
              name: "California Institute of Technology",
              tuition: 56364,
              sat_average: 1545,
              acceptance_rate: 6.4,
              location: "Pasadena, CA",
              type: "Private",
              enrollment: 2397,
              graduation_rate: 94,
              student_faculty_ratio: 3,
            },
            {
              name: "Harvey Mudd College",
              tuition: 58359,
              sat_average: 1490,
              acceptance_rate: 18.2,
              location: "Claremont, CA",
              type: "Private",
              enrollment: 906,
              graduation_rate: 87,
              student_faculty_ratio: 8,
            },
            {
              name: "Rose-Hulman Institute of Technology",
              tuition: 48804,
              sat_average: 1380,
              acceptance_rate: 61.0,
              location: "Terre Haute, IN",
              type: "Private",
              enrollment: 2104,
              graduation_rate: 74,
              student_faculty_ratio: 11,
            },
            {
              name: "Worcester Polytechnic Institute",
              tuition: 53826,
              sat_average: 1370,
              acceptance_rate: 57.5,
              location: "Worcester, MA",
              type: "Private",
              enrollment: 6808,
              graduation_rate: 86,
              student_faculty_ratio: 13,
            },
            {
              name: "Rensselaer Polytechnic Institute",
              tuition: 55378,
              sat_average: 1360,
              acceptance_rate: 65.7,
              location: "Troy, NY",
              type: "Private",
              enrollment: 7442,
              graduation_rate: 84,
              student_faculty_ratio: 15,
            },
            {
              name: "Stevens Institute of Technology",
              tuition: 54014,
              sat_average: 1350,
              acceptance_rate: 46.0,
              location: "Hoboken, NJ",
              type: "Private",
              enrollment: 6676,
              graduation_rate: 82,
              student_faculty_ratio: 10,
            },
            {
              name: "Colorado School of Mines",
              tuition: 18386,
              sat_average: 1340,
              acceptance_rate: 58.0,
              location: "Golden, CO",
              type: "Public",
              enrollment: 5612,
              graduation_rate: 76,
              student_faculty_ratio: 16,
            },
          ],
          sat_distribution: [
            { range: "1150-1200", count: 8, midpoint: 1175 },
            { range: "1200-1250", count: 12, midpoint: 1225 },
            { range: "1250-1300", count: 18, midpoint: 1275 },
            { range: "1300-1350", count: 22, midpoint: 1325 },
            { range: "1350-1400", count: 25, midpoint: 1375 },
            { range: "1400-1450", count: 20, midpoint: 1425 },
            { range: "1450-1500", count: 15, midpoint: 1475 },
            { range: "1500-1550", count: 8, midpoint: 1525 },
          ],
          demographics: [
            { region: "Northeast", white: 58.2, asian: 22.1, hispanic: 12.3, black: 5.8, other: 1.6 },
            { region: "Southeast", white: 65.4, asian: 8.9, hispanic: 15.2, black: 8.7, other: 1.8 },
            { region: "Midwest", white: 72.1, asian: 12.4, hispanic: 8.9, black: 5.2, other: 1.4 },
            { region: "West", white: 45.8, asian: 28.7, hispanic: 18.9, black: 4.2, other: 2.4 },
            { region: "Southwest", white: 52.3, asian: 15.2, hispanic: 25.8, black: 4.9, other: 1.8 },
            { region: "Mountain", white: 68.9, asian: 9.8, hispanic: 16.2, black: 3.4, other: 1.7 },
          ],
          summary_stats: {
            avg_acceptance_rate: 45.8,
            total_applications: "12.8M",
            avg_tuition: 28450,
            avg_sat: 1345,
          },
          regional_analysis: {},
        }

        setData(mockData)
        setLoading(false)
      } catch (err) {
        setError(err instanceof Error ? err.message : "Failed to load data")
        setLoading(false)
      }
    }

    loadData()
  }, [])

  useEffect(() => {
    if (!data) {
      setFilteredData(null)
      return
    }

    if (selectedColleges.length === 0) {
      setFilteredData(data)
      return
    }

    const filtered = {
      ...data,
      acceptance_rates: data.acceptance_rates.filter((college) => selectedColleges.includes(college.name)),
      tuition_analysis: data.tuition_analysis.filter((college) => selectedColleges.includes(college.name)),
    }

    if (filtered.tuition_analysis.length > 0) {
      const avgAcceptanceRate =
        filtered.tuition_analysis.reduce((sum, college) => sum + college.acceptance_rate, 0) /
        filtered.tuition_analysis.length
      const totalApplications = filtered.tuition_analysis.reduce(
        (sum, college) => sum + Math.round(college.enrollment * 0.05),
        0,
      )
      const avgTuition =
        filtered.tuition_analysis.reduce((sum, college) => sum + college.tuition, 0) / filtered.tuition_analysis.length
      const avgSat =
        filtered.tuition_analysis.reduce((sum, college) => sum + college.sat_average, 0) /
        filtered.tuition_analysis.length

      filtered.summary_stats = {
        avg_acceptance_rate: Math.round(avgAcceptanceRate * 10) / 10,
        total_applications: `${totalApplications}K`,
        avg_tuition: Math.round(avgTuition),
        avg_sat: Math.round(avgSat),
      }
    }

    setFilteredData(filtered)
  }, [data, selectedColleges])

  const exportData = () => {
    if (!filteredData) return

    const csvContent = [
      "College Name,Acceptance Rate,Tuition,SAT Average,Location,Type,Enrollment,Graduation Rate,Student Faculty Ratio",
      ...filteredData.tuition_analysis.map(
        (college) =>
          `"${college.name}",${college.acceptance_rate},${college.tuition},${college.sat_average},"${college.location}",${college.type},${college.enrollment},${college.graduation_rate},${college.student_faculty_ratio}`,
      ),
    ].join("\n")

    const blob = new Blob([csvContent], { type: "text/csv" })
    const url = window.URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `college-admissions-data-${new Date().toISOString().split("T")[0]}.csv`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    window.URL.revokeObjectURL(url)
  }

  return {
    data: filteredData,
    loading,
    error,
    selectedColleges,
    setSelectedColleges,
    exportData,
    colleges:
      data?.tuition_analysis.map((college) => ({
        name: college.name,
        location: college.location,
        type: college.type,
      })) || [],
  }
}
